[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$outputDirectory = Join-Path $root 'graphify-src'
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$inputs = @(
    @{ Source = 'src/Midivj ZYX.html'; Target = 'Midivj-ZYX.inline.js' },
    @{ Source = 'src/midivj-sender.html'; Target = 'midivj-sender.inline.js' }
)

foreach ($item in $inputs) {
    $sourcePath = Join-Path $root $item.Source
    if (-not (Test-Path -LiteralPath $sourcePath)) {
        throw "No se encontró la fuente: $sourcePath"
    }

    $html = [System.IO.File]::ReadAllText($sourcePath)
    $matches = [regex]::Matches(
        $html,
        '<script(?<attributes>[^>]*)>(?<body>[\s\S]*?)</script>',
        [System.Text.RegularExpressions.RegexOptions]::IgnoreCase
    )

    $parts = New-Object System.Collections.Generic.List[string]
    $parts.Add("// Generated from $($item.Source). Do not edit this file directly.")
    $parts.Add('// The original HTML remains the executable source of truth.')
    $index = 0
    foreach ($match in $matches) {
        if ($match.Groups['attributes'].Value -match '\bsrc\s*=') {
            continue
        }
        $index++
        $parts.Add("`n// ---- inline script $index ----")
        $parts.Add($match.Groups['body'].Value)
    }

    if ($index -eq 0) {
        throw "No se encontraron scripts embebidos en $($item.Source)."
    }

    $targetPath = Join-Path $outputDirectory $item.Target
    [System.IO.File]::WriteAllText($targetPath, ($parts -join "`r`n"), $utf8NoBom)
    Write-Host "Generado $($item.Target) desde $index bloque(s)."
}

$relaySource = Join-Path $root 'src/midivj-relay.js'
$relayTarget = Join-Path $outputDirectory 'midivj-relay.js'
if (-not (Test-Path -LiteralPath $relaySource)) {
    throw "No se encontró la fuente: $relaySource"
}
[System.IO.File]::Copy($relaySource, $relayTarget, $true)
Write-Host 'Copiado midivj-relay.js al corpus derivado.'
